Update init.d script

diff --git a/files/opt/etc/init.d/S55pihole-FTL b/files/opt/etc/init.d/S55pihole-FTL
--- a/files/opt/etc/init.d/S55pihole-FTL
+++ b/files/opt/etc/init.d/S55pihole-FTL
@@ -9,20 +9,13 @@ PREARGS=""
 DESC=$PROCS
 PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 
-if [ -f /opt/bin/bash ]; then
-    case $1 in
-        install)
-            # Install missing dependencies then exit
-            bash /opt/share/pihole/dependencies.sh "$1"
-            exit
-        ;;
-        start | restart)
-            # Install missing dependencies
-            bash /opt/share/pihole/dependencies.sh "$1" || exit 1
+install() {
+    # Install missing script dependencies
+    bash /opt/share/pihole/dependencies.sh "$1" || exit 1
 
-            # Set random gravity update and updatechecker times
-            # Comment/uncomment logrotate line based on binary presence
-            bash <<EOF
+    # Set random gravity update and updatechecker times
+    # Comment/uncomment logrotate line based on binary presence
+    bash <<EOF
 if [ -f "/opt/etc/cron.d/pihole" ]; then
     sed "s/59 1 /\$((1 + RANDOM % 58)) \$((3 + RANDOM % 2)) /" -i /opt/etc/cron.d/pihole
     sed "s/59 17 /\$((1 + RANDOM % 58)) \$((12 + RANDOM % 8)) /" -i /opt/etc/cron.d/pihole
@@ -35,9 +28,22 @@ if [ -f "/opt/etc/cron.d/pihole" ]; then
 fi
 EOF
 
-            # Make sure gravity database exists
-            PI_HOLE_DBFILE="$(pihole-FTL --config -q files.gravity)"
-            [ -n "$PI_HOLE_DBFILE" ] && [ ! -f "$PI_HOLE_DBFILE" ] && pihole -g
+    # Make sure gravity database exists
+    PI_HOLE_DBFILE="$(pihole-FTL --config -q files.gravity)"
+    if [ -n "$PI_HOLE_DBFILE" ] && [ ! -f "$PI_HOLE_DBFILE" ]; then
+        pihole -g || exit 1
+    fi
+}
+
+if [ -f /opt/bin/bash ]; then
+    case $1 in
+        install)
+            install
+            exit 0
+        ;;
+        start | restart)
+            # Run install tasks silently with each start/restart
+            install "silent"
         ;;
     esac
 
