Update init script and chown handling

diff --git a/files/opt/etc/init.d/S65pihole-FTL b/files/opt/etc/init.d/S65pihole-FTL
--- a/files/opt/etc/init.d/S65pihole-FTL
+++ b/files/opt/etc/init.d/S65pihole-FTL
@@ -16,32 +16,50 @@ case $1 in
             root_user="$(id -nu 0 2> /dev/null)"
             root_group="$(id -ng 0 2> /dev/null)"
 
-            if [ -n "$root_user" ] && [ -n "$root_group" ]; then # if this is empty then this can indicate absence of 'id' command
-                if [ -n "$(id -u pihole 2> /dev/null)" ]; then
-                    ARGS="-- -u pihole -g pihole"
+            if [ -z "$root_user" ] || [ -z "$root_group" ]; then
+                echo "Error: Unable to find root user or group" >&2
+                exit 1
+            fi
 
-                    # Update permissions of /dev/shm to allow pihole user to delete their own files and create new ones
-                    if [ "$(stat -c "%a" /dev/shm)" != "1777" ]; then
-                        if ! chmod 1777 /dev/shm; then
-                            echo "Warning: Failed to update permissions of /dev/shm" >&2
-                        fi
-                    fi
+            #shellcheck disable=SC1091
+            . /opt/share/pihole/utils.sh
+            run_as_user="$(getRunAsUser)"
 
-                    # attempt to start the intended way
-                    if setcap CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_NET_ADMIN,CAP_SYS_NICE,CAP_IPC_LOCK,CAP_CHOWN+eip "/opt/bin/pihole-FTL"; then
-                        PREARGS="nonroot pihole"
-                    else
-                        echo "Warning: Starting pihole-FTL as '$root_user' (then dropping to 'pihole') because setting capabilities is not supported on this system" >&2
-                    fi
-                else # start as root user
+            # User can choose to force to run as root...
+            if [ "$run_as_user" = "root" ] || [ "$run_as_user" = "$root_user" ]; then
+                run_as_user=
+            fi
+
+            # Update permissions of /dev/shm to allow non-root users to create and delete files
+            if [ -n "$run_as_user" ] && [ "$(stat -c "%a" /dev/shm)" != "1777" ]; then
+                if ! chmod 1777 /dev/shm; then
+                    echo "Warning: Failed to update permissions of /dev/shm" >&2
+                fi
+            fi
+
+            # Check if we can start the daemon the intended way
+            if
+                [ -n "$run_as_user" ] && \
+                setcap CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_NET_ADMIN,CAP_SYS_NICE,CAP_IPC_LOCK,CAP_CHOWN+eip "/opt/bin/pihole-FTL"
+            then
+                PREARGS="nonroot $run_as_user"
+                ARGS="-- -u $run_as_user -g $run_as_user" # even when user will be 'pihole' we need to specify this, for some reason
+
+                #if [ "$run_as_user" != "pihole" ]; then # without this it will try to use hardcoded 'pihole' user
+                #    ARGS="-- -u $run_as_user -g $run_as_user"
+                #fi
+            else
+                echo "Warning: Starting in an unsupported way - expect issues to happen!" >&2
+
+                if [ -n "$run_as_user" ]; then
+                    ARGS="-- -u $run_as_user -g $run_as_user"
+
+                    echo "Warning: Starting pihole-FTL as '$root_user' (then changing to '$run_as_user') because setting capabilities is not supported on this system" >&2
+                else
                     ARGS="-- -u $root_user -g $root_group" # workaround for "[dnsmasq] unknown user or group: root" error
 
-                    echo "Warning: Starting pihole-FTL as '$root_user' because 'pihole' user does not exist" >&2
-
-                    chown -R "$root_user":"$root_group" /opt/etc/pihole /opt/var/log/pihole
+                    echo "Warning: Starting pihole-FTL as '$root_user' because couldn't find suitable user to run as" >&2
                 fi
-            else
-                echo "Warning: Unable to determine root user" >&2
             fi
         fi
 
@@ -55,8 +73,8 @@ esac
 . /opt/etc/init.d/rc.func
 
 case $1 in
-    stop | kill)
-        # Run poststop script after stop/kill
+    stop)
+        # Run poststop script after stop
         bash /opt/share/pihole/pihole-FTL-poststop.sh
     ;;
 esac
