Prepare for new release

diff --git a/patches/core-002-replace-service-calls.patch b/patches/core-002-replace-service-calls.patch
--- a/patches/core-002-replace-service-calls.patch
+++ b/patches/core-002-replace-service-calls.patch
@@ -20,16 +20,16 @@ index 6cc69008..c103d528 100755
 --- a/automated install/basic-install.sh	
 +++ b/automated install/basic-install.sh	
 @@ -1236,6 +1236,8 @@ stop_service() {
-     if is_pid1 systemd; then
-         # use that to restart the service
+     printf "  %b %s..." "${INFO}" "${str}"
+     if is_command systemctl; then
          systemctl -q stop "${1}" || true
 +    elif [ -f /opt/etc/opkg.conf ]; then
 +        /opt/etc/init.d/S65pihole-FTL stop >/dev/null || true
      else
-         # Otherwise, fall back to the service command
          service "${1}" stop >/dev/null || true
+     fi
 @@ -1252,6 +1254,8 @@ restart_service() {
-     if is_pid1 systemd; then
+     if is_command systemctl; then
          # use that to restart the service
          systemctl -q restart "${1}"
 +    elif [ -f /opt/etc/opkg.conf ]; then
@@ -37,3 +37,59 @@ index 6cc69008..c103d528 100755
      else
          # Otherwise, fall back to the service command
          service "${1}" restart >/dev/null
+diff --git a/advanced/Scripts/piholeARPTable.sh b/advanced/Scripts/piholeARPTable.sh
+index f55b1320..6f984bbb 100755
+--- a/advanced/Scripts/piholeARPTable.sh
++++ b/advanced/Scripts/piholeARPTable.sh
+@@ -32,7 +32,7 @@ flushARP(){
+     fi
+ 
+     # Stop FTL to prevent database access
+-    if ! output=$(service pihole-FTL stop 2>&1); then
++    if ! output=$(/opt/etc/init.d/S65pihole-FTL stop 2>&1); then
+         echo -e "${OVER}  ${CROSS} Failed to stop FTL"
+         echo "  Output: ${output}"
+         return 1
+@@ -64,7 +64,7 @@ flushARP(){
+     fi
+ 
+     # Start FTL again
+-    if ! output=$(service pihole-FTL restart 2>&1); then
++    if ! output=$(/opt/etc/init.d/S65pihole-FTL restart 2>&1); then
+         echo -e "${OVER}  ${CROSS} Failed to restart FTL"
+         echo "  Output: ${output}"
+         return 1
+diff --git a/advanced/Scripts/piholeDebug.sh b/advanced/Scripts/piholeDebug.sh
+index f4226299..5b1b2cfd 100755
+--- a/advanced/Scripts/piholeDebug.sh
++++ b/advanced/Scripts/piholeDebug.sh
+@@ -849,7 +849,7 @@ process_status(){
+                 :
+             else
+             # non-Docker system
+-                if service "${i}" status | grep -E 'is\srunning' &> /dev/null; then
++                if /opt/etc/init.d/S65pihole-FTL check | grep -q 'alive' &> /dev/null; then
+                     status_of_process="active"
+                 else
+                     status_of_process="inactive"
+diff --git a/advanced/Scripts/piholeLogFlush.sh b/advanced/Scripts/piholeLogFlush.sh
+index 34d96318..f905f045 100755
+--- a/advanced/Scripts/piholeLogFlush.sh
++++ b/advanced/Scripts/piholeLogFlush.sh
+@@ -108,13 +108,14 @@ else
+     fi
+ 
+     # Stop FTL to make sure it doesn't write to the database while we're deleting data
+-    service pihole-FTL stop
++    /opt/etc/init.d/S65pihole-FTL stop
+ 
+     # Delete most recent 24 hours from FTL's database, leave even older data intact (don't wipe out all history)
+     deleted=$(pihole-FTL sqlite3 -ni "${DBFILE}" "DELETE FROM query_storage WHERE timestamp >= strftime('%s','now')-86400; select changes() from query_storage limit 1")
+ 
+     # Restart FTL
+-    service pihole-FTL restart
++    /opt/etc/init.d/S65pihole-FTL restart
++
+     if [[ "$*" != *"quiet"* ]]; then
+         echo -e "${OVER}  ${TICK} Deleted ${deleted} queries from long-term query database"
+     fi
